name: bloc_infinite_list
description: BLoC Infinite ListTutorial
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  stream_transform: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true